/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            ok: boolean;
            /** @description Hedera chainId the gateway authorizes against (296 = testnet) */
            chainId: number;
        };
        /**
         * @description Stable public contract. The canonical list lives in `packages/shared/src/errors.ts`;
         *     this enum only mirrors it (T039 verifies the two stay identical). Do not rename values.
         * @enum {string}
         */
        ErrorCode: "RECEIPT_ALREADY_CONSUMED" | "RESOURCE_HASH_MISMATCH" | "POLICY_HASH_MISMATCH" | "CHAIN_ID_MISMATCH" | "LICENSEE_MISMATCH" | "RECEIPT_EXPIRED" | "USE_LIMIT_EXCEEDED" | "UNDERPAYMENT" | "PAYMENT_ID_PAYLOAD_CONFLICT" | "OWNER_EPOCH_MISMATCH" | "LICENSE_INVALIDATED_ON_TRANSFER" | "LICENSE_EPOCH_MISMATCH";
        Error: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            detail?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
