// Copies the compiled RightsNFT / RightsRegistry ABIs from apps/contracts (Hardhat artifacts)
// into src/chain/abi.ts as `as const` arrays so viem can infer argument / return types.
//   pnpm --filter gateway sync-abis   (run after `pnpm --filter contracts compile`)
// The generated file is committed; CI re-runs this script and fails on drift.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifacts = resolve(here, "../../contracts/artifacts/contracts");
const outFile = resolve(here, "../src/chain/abi.ts");

type AbiEntry = { type: string; name?: string };

function loadAbi(name: string): AbiEntry[] {
  const path = resolve(artifacts, `${name}.sol/${name}.json`);
  const artifact = JSON.parse(readFileSync(path, "utf8")) as { abi?: unknown };
  if (!Array.isArray(artifact.abi)) throw new Error(`no abi in ${path}`);
  return artifact.abi as AbiEntry[];
}

const nft = loadAbi("RightsNFT");
const registry = loadAbi("RightsRegistry");
const banner = `// GENERATED by scripts/sync-abis.ts from apps/contracts artifacts - do not edit.
// RightsNFT: ${nft.length} entries, RightsRegistry: ${registry.length} entries.
`;
const body = `${banner}
export const rightsNftAbi = ${JSON.stringify(nft, null, 2)} as const;

export const rightsRegistryAbi = ${JSON.stringify(registry, null, 2)} as const;
`;
mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
console.log(`wrote ${outFile}`);
